// <auto-generated />
using System;
using Maliev.MaterialService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.MaterialService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    partial class MaterialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColorMaterial", b =>
                {
                    b.Property<Guid>("AvailableColorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("available_colors_id");

                    b.Property<Guid>("MaterialsId")
                        .HasColumnType("uuid")
                        .HasColumnName("materials_id");

                    b.HasKey("AvailableColorsId", "MaterialsId")
                        .HasName("pk_material_colors");

                    b.HasIndex("MaterialsId")
                        .HasDatabaseName("ix_material_colors_materials_id");

                    b.ToTable("material_colors", (string)null);
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("HexCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("hex_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_colors");

                    b.HasIndex("HexCode")
                        .IsUnique()
                        .HasDatabaseName("ix_colors_hex_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_colors_name");

                    b.ToTable("colors");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_manufacturing_processes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturing_processes_name");

                    b.ToTable("manufacturing_processes");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_per_unit");

                    b.Property<int>("StockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("stock_level");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_materials_active");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_materials_created_at");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_name");

                    b.HasIndex("PricePerUnit")
                        .HasDatabaseName("ix_materials_price_per_unit");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_materials_supplier_id");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MaterialMechanicalProperty", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid>("MechanicalPropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("mechanical_property_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("MaterialId", "MechanicalPropertyId")
                        .HasName("pk_material_mechanical_properties");

                    b.HasIndex("MechanicalPropertyId")
                        .HasDatabaseName("ix_material_mechanical_properties_mechanical_property_id");

                    b.ToTable("material_mechanical_properties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MechanicalProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_mechanical_properties");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mechanical_properties_name");

                    b.ToTable("mechanical_properties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.PostProcessingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_post_processing_methods");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_post_processing_methods_name");

                    b.ToTable("post_processing_methods");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contact_info");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("ManufacturingProcessMaterial", b =>
                {
                    b.Property<Guid>("ManufacturingProcessesId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturing_processes_id");

                    b.Property<Guid>("MaterialsId")
                        .HasColumnType("uuid")
                        .HasColumnName("materials_id");

                    b.HasKey("ManufacturingProcessesId", "MaterialsId")
                        .HasName("pk_material_manufacturing_processes");

                    b.HasIndex("MaterialsId")
                        .HasDatabaseName("ix_material_manufacturing_processes_materials_id");

                    b.ToTable("material_manufacturing_processes", (string)null);
                });

            modelBuilder.Entity("MaterialPostProcessingMethod", b =>
                {
                    b.Property<Guid>("MaterialsId")
                        .HasColumnType("uuid")
                        .HasColumnName("materials_id");

                    b.Property<Guid>("PostProcessingMethodsId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_processing_methods_id");

                    b.HasKey("MaterialsId", "PostProcessingMethodsId")
                        .HasName("pk_material_post_processing_methods");

                    b.HasIndex("PostProcessingMethodsId")
                        .HasDatabaseName("ix_material_post_processing_methods_post_processing_methods_id");

                    b.ToTable("material_post_processing_methods", (string)null);
                });

            modelBuilder.Entity("ColorMaterial", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("AvailableColorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_colors__colors_available_colors_id");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_colors__materials_materials_id");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Material", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Materials")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_materials__suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MaterialMechanicalProperty", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", "Material")
                        .WithMany("MechanicalProperties")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_mechanical_properties_materials_material_id");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.MechanicalProperty", "MechanicalProperty")
                        .WithMany("MaterialMechanicalProperties")
                        .HasForeignKey("MechanicalPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_mechanical_properties__mechanical_properties_mechani~");

                    b.Navigation("Material");

                    b.Navigation("MechanicalProperty");
                });

            modelBuilder.Entity("ManufacturingProcessMaterial", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", null)
                        .WithMany()
                        .HasForeignKey("ManufacturingProcessesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_manufacturing_processes_manufacturing_processes_ma~");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_manufacturing_processes_materials_materials_id");
                });

            modelBuilder.Entity("MaterialPostProcessingMethod", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_post_processing_methods_materials_materials_id");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.PostProcessingMethod", null)
                        .WithMany()
                        .HasForeignKey("PostProcessingMethodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_post_processing_methods_post_processing_methods_po~");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Material", b =>
                {
                    b.Navigation("MechanicalProperties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MechanicalProperty", b =>
                {
                    b.Navigation("MaterialMechanicalProperties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
