// <auto-generated />
using System;
using Maliev.MaterialService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.MaterialService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    [Migration("20260325114603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColorMaterial", b =>
                {
                    b.Property<Guid>("AvailableColorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("available_colors_id");

                    b.Property<Guid>("MaterialsId")
                        .HasColumnType("uuid")
                        .HasColumnName("materials_id");

                    b.HasKey("AvailableColorsId", "MaterialsId")
                        .HasName("pk_material_colors");

                    b.HasIndex("MaterialsId")
                        .HasDatabaseName("ix_material_colors_materials_id");

                    b.ToTable("material_colors", (string)null);
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("HexCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("hex_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_colors");

                    b.HasIndex("HexCode")
                        .IsUnique()
                        .HasDatabaseName("ix_colors_hex_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_colors_name");

                    b.ToTable("colors");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_manufacturing_processes");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_manufacturing_processes_active");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturing_processes_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturing_processes_name");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_manufacturing_processes_sort_order");

                    b.ToTable("manufacturing_processes");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("DensityGCm3")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("density_g_cm3");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("MachinabilityRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("machinability_rating");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_per_unit");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("StockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("stock_level");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_materials_active");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_materials_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_materials_created_at");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_name");

                    b.HasIndex("PricePerUnit")
                        .HasDatabaseName("ix_materials_price_per_unit");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_materials_sort_order");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_materials_supplier_id");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MaterialMechanicalProperty", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid>("MechanicalPropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("mechanical_property_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("MaterialId", "MechanicalPropertyId")
                        .HasName("pk_material_mechanical_properties");

                    b.HasIndex("MechanicalPropertyId")
                        .HasDatabaseName("ix_material_mechanical_properties_mechanical_property_id");

                    b.ToTable("material_mechanical_properties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MechanicalProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_mechanical_properties");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mechanical_properties_name");

                    b.ToTable("mechanical_properties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.PostProcessingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_post_processing_methods");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_post_processing_methods_name");

                    b.ToTable("post_processing_methods");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.ProcessConfigOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("config_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ManufacturingProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturing_process_id");

                    b.Property<string>("OptionsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("options_json");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_process_config_options");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_process_config_options_active");

                    b.HasIndex("ManufacturingProcessId", "ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_process_config_options_manufacturing_process_id_config_key");

                    b.ToTable("process_config_options");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contact_info");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.SurfaceFinish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<decimal>("AdditionalCostPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("additional_cost_percent");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("RaValueUm")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("ra_value_um");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_surface_finishes");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_surface_finishes_active");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_surface_finishes_code");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_surface_finishes_sort_order");

                    b.ToTable("surface_finishes");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.ToleranceClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<decimal>("AdditionalCostPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("additional_cost_percent");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<string>("IsoStandard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("iso_standard");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("ToleranceRange")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tolerance_range");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tolerance_classes");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_tolerance_classes_active");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tolerance_classes_code");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_tolerance_classes_sort_order");

                    b.ToTable("tolerance_classes");
                });

            modelBuilder.Entity("ManufacturingProcessMaterial", b =>
                {
                    b.Property<Guid>("ManufacturingProcessesId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturing_processes_id");

                    b.Property<Guid>("MaterialsId")
                        .HasColumnType("uuid")
                        .HasColumnName("materials_id");

                    b.HasKey("ManufacturingProcessesId", "MaterialsId")
                        .HasName("pk_material_manufacturing_processes");

                    b.HasIndex("MaterialsId")
                        .HasDatabaseName("ix_material_manufacturing_processes_materials_id");

                    b.ToTable("material_manufacturing_processes", (string)null);
                });

            modelBuilder.Entity("ManufacturingProcessSurfaceFinish", b =>
                {
                    b.Property<Guid>("AvailableForProcessesId")
                        .HasColumnType("uuid")
                        .HasColumnName("available_for_processes_id");

                    b.Property<Guid>("SurfaceFinishesId")
                        .HasColumnType("uuid")
                        .HasColumnName("surface_finishes_id");

                    b.HasKey("AvailableForProcessesId", "SurfaceFinishesId")
                        .HasName("pk_surface_finish_processes");

                    b.HasIndex("SurfaceFinishesId")
                        .HasDatabaseName("ix_surface_finish_processes_surface_finishes_id");

                    b.ToTable("surface_finish_processes", (string)null);
                });

            modelBuilder.Entity("ManufacturingProcessToleranceClass", b =>
                {
                    b.Property<Guid>("AvailableForProcessesId")
                        .HasColumnType("uuid")
                        .HasColumnName("available_for_processes_id");

                    b.Property<Guid>("ToleranceClassesId")
                        .HasColumnType("uuid")
                        .HasColumnName("tolerance_classes_id");

                    b.HasKey("AvailableForProcessesId", "ToleranceClassesId")
                        .HasName("pk_tolerance_class_processes");

                    b.HasIndex("ToleranceClassesId")
                        .HasDatabaseName("ix_tolerance_class_processes_tolerance_classes_id");

                    b.ToTable("tolerance_class_processes", (string)null);
                });

            modelBuilder.Entity("MaterialPostProcessingMethod", b =>
                {
                    b.Property<Guid>("MaterialsId")
                        .HasColumnType("uuid")
                        .HasColumnName("materials_id");

                    b.Property<Guid>("PostProcessingMethodsId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_processing_methods_id");

                    b.HasKey("MaterialsId", "PostProcessingMethodsId")
                        .HasName("pk_material_post_processing_methods");

                    b.HasIndex("PostProcessingMethodsId")
                        .HasDatabaseName("ix_material_post_processing_methods_post_processing_methods_id");

                    b.ToTable("material_post_processing_methods", (string)null);
                });

            modelBuilder.Entity("MaterialSurfaceFinish", b =>
                {
                    b.Property<Guid>("CompatibleMaterialsId")
                        .HasColumnType("uuid")
                        .HasColumnName("compatible_materials_id");

                    b.Property<Guid>("SurfaceFinishesId")
                        .HasColumnType("uuid")
                        .HasColumnName("surface_finishes_id");

                    b.HasKey("CompatibleMaterialsId", "SurfaceFinishesId")
                        .HasName("pk_surface_finish_materials");

                    b.HasIndex("SurfaceFinishesId")
                        .HasDatabaseName("ix_surface_finish_materials_surface_finishes_id");

                    b.ToTable("surface_finish_materials", (string)null);
                });

            modelBuilder.Entity("ColorMaterial", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("AvailableColorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_colors__colors_available_colors_id");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_colors__materials_materials_id");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Material", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Materials")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_materials__suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MaterialMechanicalProperty", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", "Material")
                        .WithMany("MechanicalProperties")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_mechanical_properties_materials_material_id");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.MechanicalProperty", "MechanicalProperty")
                        .WithMany("MaterialMechanicalProperties")
                        .HasForeignKey("MechanicalPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_mechanical_properties__mechanical_properties_mechani~");

                    b.Navigation("Material");

                    b.Navigation("MechanicalProperty");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.ProcessConfigOption", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", "ManufacturingProcess")
                        .WithMany("ConfigOptions")
                        .HasForeignKey("ManufacturingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_config_options_manufacturing_processes_manufacturin~");

                    b.Navigation("ManufacturingProcess");
                });

            modelBuilder.Entity("ManufacturingProcessMaterial", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", null)
                        .WithMany()
                        .HasForeignKey("ManufacturingProcessesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_manufacturing_processes_manufacturing_processes_ma~");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_manufacturing_processes_materials_materials_id");
                });

            modelBuilder.Entity("ManufacturingProcessSurfaceFinish", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", null)
                        .WithMany()
                        .HasForeignKey("AvailableForProcessesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surface_finish_processes_manufacturing_processes_available_~");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.SurfaceFinish", null)
                        .WithMany()
                        .HasForeignKey("SurfaceFinishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surface_finish_processes_surface_finishes_surface_finishes_~");
                });

            modelBuilder.Entity("ManufacturingProcessToleranceClass", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", null)
                        .WithMany()
                        .HasForeignKey("AvailableForProcessesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tolerance_class_processes_manufacturing_processes_available~");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.ToleranceClass", null)
                        .WithMany()
                        .HasForeignKey("ToleranceClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tolerance_class_processes_tolerance_classes_tolerance_class~");
                });

            modelBuilder.Entity("MaterialPostProcessingMethod", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_post_processing_methods_materials_materials_id");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.PostProcessingMethod", null)
                        .WithMany()
                        .HasForeignKey("PostProcessingMethodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_post_processing_methods_post_processing_methods_po~");
                });

            modelBuilder.Entity("MaterialSurfaceFinish", b =>
                {
                    b.HasOne("Maliev.MaterialService.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("CompatibleMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surface_finish_materials_materials_compatible_materials_id");

                    b.HasOne("Maliev.MaterialService.Domain.Entities.SurfaceFinish", null)
                        .WithMany()
                        .HasForeignKey("SurfaceFinishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surface_finish_materials_surface_finishes_surface_finishes_~");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.ManufacturingProcess", b =>
                {
                    b.Navigation("ConfigOptions");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Material", b =>
                {
                    b.Navigation("MechanicalProperties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.MechanicalProperty", b =>
                {
                    b.Navigation("MaterialMechanicalProperties");
                });

            modelBuilder.Entity("Maliev.MaterialService.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
