//----------------------
// <auto-generated>
//     Generated on 2025-12-20 10:52:52 UTC
// </auto-generated>
//----------------------

using System.Text.Json.Serialization;

namespace Maliev.MessagingContracts.Generated
{
    /// <summary>
    /// The base structure that all Maliev messaging contracts MUST adhere to.
    /// </summary>
    /// <param name="MessageId">Unique identifier for the message.</param>
    /// <param name="MessageName">Name of the message.</param>
    /// <param name="MessageType">Type of the message.</param>
    /// <param name="MessageVersion">Version of the message contract.</param>
    /// <param name="PublishedBy">Service that published the message.</param>
    /// <param name="ConsumedBy">List of services that consumed the message.</param>
    /// <param name="CorrelationId">Correlation ID for tracking message flows.</param>
    /// <param name="CausationId">Optional causation ID.</param>
    /// <param name="OccurredAtUtc">Timestamp when the event occurred.</param>
    /// <param name="IsPublic">Indicates if the message is public.</param>
    public record BaseMessage(
        [property: JsonPropertyName("messageId")] System.Guid MessageId,
        [property: JsonPropertyName("messageName")] string MessageName,
        [property: JsonPropertyName("messageType")] MessageType MessageType,
        [property: JsonPropertyName("messageVersion")] string MessageVersion,
        [property: JsonPropertyName("publishedBy")] string PublishedBy,
        [property: JsonPropertyName("consumedBy")] System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        [property: JsonPropertyName("correlationId")] System.Guid CorrelationId,
        [property: JsonPropertyName("causationId")] System.Guid? CausationId,
        [property: JsonPropertyName("occurredAtUtc")] System.DateTimeOffset OccurredAtUtc,
        [property: JsonPropertyName("isPublic")] bool IsPublic
    );

    /// <summary>
    /// Defines the type of message.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MessageType
    {
        /// <summary>A command message.</summary>
        Command,
        /// <summary>An event message.</summary>
        Event,
        /// <summary>A request message.</summary>
        Request,
        /// <summary>A response message.</summary>
        Response
    }

    /// <summary>
    /// Payload for CreateUserCommand.
    /// </summary>
    /// <param name="Username">Username.</param>
    /// <param name="Email">Email.</param>
    public record CreateUserCommandPayload([property: JsonPropertyName("username")] string Username, [property: JsonPropertyName("email")] string Email);

    /// <summary>
    /// Command message for user creation.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record CreateUserCommand(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] CreateUserCommandPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for CustomerDetailsResponse.
    /// </summary>
    /// <param name="CustomerId">Customer ID.</param>
    /// <param name="FullName">Full Name.</param>
    /// <param name="Email">Email.</param>
    public record CustomerDetailsResponsePayload([property: JsonPropertyName("customerId")] System.Guid CustomerId, [property: JsonPropertyName("fullName")] string FullName, [property: JsonPropertyName("email")] string Email);

    /// <summary>
    /// Response message for customer details.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record CustomerDetailsResponse(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] CustomerDetailsResponsePayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for GetCustomerDetailsRequest.
    /// </summary>
    /// <param name="CustomerId">Customer ID.</param>
    public record GetCustomerDetailsRequestPayload([property: JsonPropertyName("customerId")] System.Guid CustomerId);

    /// <summary>
    /// Request message for customer details.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record GetCustomerDetailsRequest(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] GetCustomerDetailsRequestPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for PermissionRegisteredEvent.
    /// </summary>
    /// <param name="PermissionId">Permission ID.</param>
    /// <param name="ServiceName">Service Name.</param>
    /// <param name="ResourceType">Resource Type.</param>
    /// <param name="Action">Action.</param>
    /// <param name="RegisteredAt">Registered At.</param>
    public record PermissionRegisteredEventPayload([property: JsonPropertyName("permissionId")] string PermissionId, [property: JsonPropertyName("serviceName")] string ServiceName, [property: JsonPropertyName("resourceType")] string ResourceType, [property: JsonPropertyName("action")] string Action, [property: JsonPropertyName("registeredAt")] System.DateTimeOffset RegisteredAt);

    /// <summary>
    /// Event message for permission registration.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record PermissionRegisteredEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] PermissionRegisteredEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for PrincipalRoleGrantedEvent.
    /// </summary>
    /// <param name="BindingId">Binding ID.</param>
    /// <param name="PrincipalId">Principal ID.</param>
    /// <param name="RoleId">Role ID.</param>
    /// <param name="ResourceType">Resource Type.</param>
    /// <param name="ResourceId">Resource ID.</param>
    /// <param name="GrantedAt">Granted At.</param>
    /// <param name="ExpiresAt">Expires At.</param>
    public record PrincipalRoleGrantedEventPayload([property: JsonPropertyName("bindingId")] System.Guid BindingId, [property: JsonPropertyName("principalId")] System.Guid PrincipalId, [property: JsonPropertyName("roleId")] string RoleId, [property: JsonPropertyName("resourceType")] string ResourceType, [property: JsonPropertyName("resourceId")] string ResourceId, [property: JsonPropertyName("grantedAt")] System.DateTimeOffset GrantedAt, [property: JsonPropertyName("expiresAt")] System.DateTimeOffset ExpiresAt);

    /// <summary>
    /// Event message for principal role grant.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record PrincipalRoleGrantedEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] PrincipalRoleGrantedEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for PrincipalRoleRevokedEvent.
    /// </summary>
    /// <param name="BindingId">Binding ID.</param>
    /// <param name="PrincipalId">Principal ID.</param>
    /// <param name="RoleId">Role ID.</param>
    /// <param name="RevokedAt">Revoked At.</param>
    public record PrincipalRoleRevokedEventPayload([property: JsonPropertyName("bindingId")] System.Guid BindingId, [property: JsonPropertyName("principalId")] System.Guid PrincipalId, [property: JsonPropertyName("roleId")] string RoleId, [property: JsonPropertyName("revokedAt")] System.DateTimeOffset RevokedAt);

    /// <summary>
    /// Event message for principal role revocation.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record PrincipalRoleRevokedEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] PrincipalRoleRevokedEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for RoleUpdatedEvent.
    /// </summary>
    /// <param name="RoleId">Role ID.</param>
    /// <param name="ServiceName">Service Name.</param>
    /// <param name="UpdatedAt">Updated At.</param>
    public record RoleUpdatedEventPayload([property: JsonPropertyName("roleId")] string RoleId, [property: JsonPropertyName("serviceName")] string ServiceName, [property: JsonPropertyName("updatedAt")] System.DateTimeOffset UpdatedAt);

    /// <summary>
    /// Event message for role update.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record RoleUpdatedEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] RoleUpdatedEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for CreateOrderCommand.
    /// </summary>
    /// <param name="OrderId">Order ID.</param>
    /// <param name="CustomerId">Customer ID.</param>
    /// <param name="Amount">Amount.</param>
    /// <param name="Currency">Currency.</param>
    public record CreateOrderCommandPayload([property: JsonPropertyName("orderId")] System.Guid OrderId, [property: JsonPropertyName("customerId")] System.Guid CustomerId, [property: JsonPropertyName("amount")] double Amount, [property: JsonPropertyName("currency")] string Currency);

    /// <summary>
    /// Command message for order creation.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record CreateOrderCommand(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] CreateOrderCommandPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for PaymentCompletedEvent.
    /// </summary>
    /// <param name="OrderId">Order ID.</param>
    /// <param name="PaymentId">Payment ID.</param>
    /// <param name="Amount">Amount.</param>
    /// <param name="Currency">Currency.</param>
    public record PaymentCompletedEventPayload([property: JsonPropertyName("orderId")] System.Guid OrderId, [property: JsonPropertyName("paymentId")] System.Guid PaymentId, [property: JsonPropertyName("amount")] double Amount, [property: JsonPropertyName("currency")] string Currency);

    /// <summary>
    /// Event message for payment completion.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record PaymentCompletedEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] PaymentCompletedEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for PaymentCreatedEvent.
    /// </summary>
    /// <param name="TransactionId">Transaction ID.</param>
    /// <param name="IdempotencyKey">Idempotency Key.</param>
    /// <param name="Amount">Amount.</param>
    /// <param name="Currency">Currency.</param>
    /// <param name="CustomerId">Customer ID.</param>
    /// <param name="OrderId">Order ID.</param>
    /// <param name="ProviderName">Provider Name.</param>
    public record PaymentCreatedEventPayload([property: JsonPropertyName("transactionId")] System.Guid TransactionId, [property: JsonPropertyName("idempotencyKey")] string IdempotencyKey, [property: JsonPropertyName("amount")] double Amount, [property: JsonPropertyName("currency")] string Currency, [property: JsonPropertyName("customerId")] string CustomerId, [property: JsonPropertyName("orderId")] string OrderId, [property: JsonPropertyName("providerName")] string ProviderName);

    /// <summary>
    /// Event message for payment creation.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record PaymentCreatedEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] PaymentCreatedEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Payload for PaymentFailedEvent.
    /// </summary>
    /// <param name="TransactionId">Transaction ID.</param>
    /// <param name="IdempotencyKey">Idempotency Key.</param>
    /// <param name="Amount">Amount.</param>
    /// <param name="Currency">Currency.</param>
    /// <param name="CustomerId">Customer ID.</param>
    /// <param name="OrderId">Order ID.</param>
    /// <param name="ProviderName">Provider Name.</param>
    /// <param name="ErrorMessage">Error Message.</param>
    /// <param name="ProviderErrorCode">Provider Error Code.</param>
    /// <param name="FailedAt">Failed At.</param>
    public record PaymentFailedEventPayload([property: JsonPropertyName("transactionId")] System.Guid TransactionId, [property: JsonPropertyName("idempotencyKey")] string IdempotencyKey, [property: JsonPropertyName("amount")] double Amount, [property: JsonPropertyName("currency")] string Currency, [property: JsonPropertyName("customerId")] string CustomerId, [property: JsonPropertyName("orderId")] string OrderId, [property: JsonPropertyName("providerName")] string ProviderName, [property: JsonPropertyName("errorMessage")] string ErrorMessage, [property: JsonPropertyName("providerErrorCode")] string ProviderErrorCode, [property: JsonPropertyName("failedAt")] System.DateTimeOffset FailedAt);

    /// <summary>
    /// Event message for payment failure.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record PaymentFailedEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] PaymentFailedEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

    /// <summary>
    /// Target user for a notification.
    /// </summary>
    /// <param name="UserId">User ID.</param>
    /// <param name="UserType">User Type.</param>
    public record NotificationEventPayloadTargetUsersItem([property: JsonPropertyName("userId")] string UserId, [property: JsonPropertyName("userType")] string UserType);

    /// <summary>
    /// Metadata for NotificationEventPayload.
    /// </summary>
    /// <param name="Language">Language.</param>
    /// <param name="Source">Source.</param>
    public record NotificationEventPayloadMetadata([property: JsonPropertyName("language")] string Language, [property: JsonPropertyName("source")] string Source);

    /// <summary>
    /// Payload for NotificationEvent.
    /// </summary>
    /// <param name="NotificationType">Notification Type.</param>
    /// <param name="Priority">Priority.</param>
    /// <param name="TargetUsers">Target Users.</param>
    /// <param name="TemplateId">Template ID.</param>
    /// <param name="Parameters">Parameters.</param>
    /// <param name="Metadata">Metadata.</param>
    public record NotificationEventPayload([property: JsonPropertyName("notificationType")] string NotificationType, [property: JsonPropertyName("priority")] string Priority, [property: JsonPropertyName("targetUsers")] System.Collections.Generic.IReadOnlyList<NotificationEventPayloadTargetUsersItem> TargetUsers, [property: JsonPropertyName("templateId")] string TemplateId, [property: JsonPropertyName("parameters")] object Parameters, [property: JsonPropertyName("metadata")] NotificationEventPayloadMetadata Metadata);

    /// <summary>
    /// Event message for notifications.
    /// </summary>
    /// <param name="MessageId">Message ID.</param>
    /// <param name="MessageName">Message Name.</param>
    /// <param name="MessageType">Message Type.</param>
    /// <param name="MessageVersion">Message Version.</param>
    /// <param name="PublishedBy">Published By.</param>
    /// <param name="ConsumedBy">Consumed By.</param>
    /// <param name="CorrelationId">Correlation Id.</param>
    /// <param name="CausationId">Causation Id.</param>
    /// <param name="OccurredAtUtc">Occurred At UTC.</param>
    /// <param name="IsPublic">Is Public.</param>
    /// <param name="Payload">Payload.</param>
    public record NotificationEvent(
        System.Guid MessageId,
        string MessageName,
        MessageType MessageType,
        string MessageVersion,
        string PublishedBy,
        System.Collections.Generic.IReadOnlyList<string> ConsumedBy,
        System.Guid CorrelationId,
        System.Guid? CausationId,
        System.DateTimeOffset OccurredAtUtc,
        bool IsPublic,
        [property: JsonPropertyName("payload")] NotificationEventPayload Payload
    ) : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic);

}
